backend:
  name: github
  repo: catherinesiller/catherine-siller

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    folder: src/pages/blog
    label: Blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }